create table if not exists site_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  session_id text,
  created_at timestamptz not null default now()
);

create index if not exists site_events_event_name_idx
on site_events (event_name);

create index if not exists site_events_created_at_idx
on site_events (created_at);

create table if not exists questionnaire_questions (
  id text primary key,
  question_order integer not null unique,
  question_kind text not null default 'scored' check (question_kind in ('scored', 'special')),
  question_en text not null,
  question_th text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table questionnaire_questions
add column if not exists question_kind text not null default 'scored';

create table if not exists questionnaire_choices (
  id text primary key,
  question_id text not null references questionnaire_questions (id) on delete cascade,
  choice_order integer not null,
  label text not null,
  choice_en text not null,
  choice_th text not null,
  score_b integer not null default 0,
  score_d integer not null default 0,
  score_s integer not null default 0,
  score_m integer not null default 0,
  special_action text,
  special_url text,
  feedback_en text,
  feedback_th text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (question_id, choice_order)
);

alter table questionnaire_choices
add column if not exists special_action text;

alter table questionnaire_choices
add column if not exists special_url text;

alter table questionnaire_choices
add column if not exists feedback_en text;

alter table questionnaire_choices
add column if not exists feedback_th text;

create index if not exists questionnaire_choices_question_id_idx
on questionnaire_choices (question_id);

create table if not exists invitation_codes (
  id bigint generated by default as identity primary key,
  room_key text not null check (room_key in ('b', 'd', 's', 'm')),
  code text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists invitation_codes_room_key_idx
on invitation_codes (room_key, active);

create table if not exists invitation_results (
  id bigint generated by default as identity primary key,
  guest_name text not null,
  answered_date date not null,
  answers jsonb not null,
  scores jsonb not null,
  winning_room text not null check (winning_room in ('b', 'd', 's', 'm')),
  invitation_code text not null,
  session_id text,
  created_at timestamptz not null default now()
);

create index if not exists invitation_results_winning_room_idx
on invitation_results (winning_room);

create index if not exists invitation_results_created_at_idx
on invitation_results (created_at);

create table if not exists mini_game_scores (
  id bigint generated by default as identity primary key,
  room_key text not null check (room_key in ('b', 'd', 's', 'm')),
  guest_name text not null,
  click_count integer not null default 0,
  session_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (room_key, guest_name)
);

create index if not exists mini_game_scores_room_score_idx
on mini_game_scores (room_key, click_count desc, updated_at asc);
