create table if not exists site_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  session_id text,
  created_at timestamptz not null default now()
);

create index if not exists site_events_event_name_idx
on site_events (event_name);

create index if not exists site_events_created_at_idx
on site_events (created_at);
