/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/wrangler.jsonc --include-runtime=false cloudflare/worker-configuration.d.ts` (hash: 4a4b63df26d0f00d871bc23994afdb1a)
interface __BaseEnv_Env {
	DB: D1Database;
	ALLOWED_ORIGINS: "https://the-red-contract.netlify.app";
	READ_ONLY: "false";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "READ_ONLY">> {}
}
