const assetNames = [
  "b room profile.mp4",
  "b room sofa.mp4",
  "b room.mp4",
  "b_cover.webp",
  "b_item_1.png",
  "b_item_2.png",
  "b_item_3.png",
  "b_item_4.png",
  "b_profile.png",
  "b_room_1.png",
  "b_wall.png",
  "b-bot-end.mp4",
  "b-bot-start.mp4",
  "b-desk.png",
  "b-result.png",
  "b-room-en.png",
  "b-room-th.png",
  "b-sofa.png",
  "b-twerk.webm",
  "b1.png",
  "b2.png",
  "b3.png",
  "b4.png",
  "b5.png",
  "b6.png",
  "b7.png",
  "b8.png",
  "b9.png",
  "b10.png",
  "bell-ring.mp3",
  "black.png",
  "blue.png",
  "board.png",
  "board2.png",
  "contract_form_en.png",
  "contract_form_th.png",
  "d room profile.mp4",
  "d room sofa.mp4",
  "d room.mp4",
  "d_cover.webp",
  "d_item_1.png",
  "d_item_2.png",
  "d_item_3.png",
  "d_item_4.png",
  "d_profile.png",
  "d_room_1.png",
  "d_wall.png",
  "d-desk.PNG",
  "d-result.png",
  "d-room-en.png",
  "d-room-th.png",
  "d-sofa.png",
  "d-top-end.mp4",
  "d-top-start.mp4",
  "d-twerk.webm",
  "d1.png",
  "d2.png",
  "d3.png",
  "d4.png",
  "d5.png",
  "d6.png",
  "d7.png",
  "d8.png",
  "d9.png",
  "d10.png",
  "Decree D.mp3",
  "door_open.mp4",
  "door-knock.mp3",
  "door-open.mp3",
  "door.png",
  "en.png",
  "event.png",
  "flip.mp3",
  "green.png",
  "icon.png",
  "inside.mp4",
  "inside.png",
  "invitation-sign.png",
  "landing-page.mp4",
  "line-up-all.png",
  "line-up.mp4",
  "lobby-video.mp4",
  "lobby.png",
  "lyrics_b.png",
  "lyrics_d.png",
  "lyrics_m.png",
  "lyrics_s.png",
  "m room profile.mp4",
  "m room sofa.mp4",
  "m room.mp4",
  "m_cover.webp",
  "m_item_1.png",
  "m_item_2.png",
  "m_item_3.png",
  "m_item_4.png",
  "m_profile.png",
  "m_room_1.png",
  "m_wall.jpg",
  "m-bot-end.mp4",
  "m-bot-start.mp4",
  "m-desk.png",
  "m-result.png",
  "m-room-en.png",
  "m-room-th.png",
  "m-sofa.png",
  "m-twerk.webm",
  "m1.jpg",
  "m2.jpg",
  "m3.jpg",
  "m4.jpg",
  "m5.jpg",
  "m6.jpg",
  "m7.jpg",
  "m8.jpg",
  "m9.jpg",
  "m10.jpg",
  "member_en.png",
  "member_th.png",
  "Michael D.mp3",
  "michael_sound.mp3",
  "moan_b.mp3",
  "moan_d.mp3",
  "moan_m.mp3",
  "moan_s.mp3",
  "Noel M.mp3",
  "noel_sound.mp3",
  "outside.png",
  "palm.png",
  "pen.mp3",
  "photo1.png",
  "photo2.png",
  "photo3.png",
  "photo4.png",
  "poster.png",
  "red.png",
  "room-explaining.png",
  "Rosen B.mp3",
  "rosen_voice.mp3",
  "rule_en_1.png",
  "rule_en_2.png",
  "rule_th_1.png",
  "rule_th_2.png",
  "Ryusei S.mp3",
  "ryusei_sound.mp3",
  "s room profile.mp4",
  "s room sofa.mp4",
  "s room.mp4",
  "s_cover.webp",
  "s_item_1.png",
  "s_item_2.png",
  "s_item_3.png",
  "s_item_4.png",
  "s_profile.png",
  "s_room_1.png",
  "s_wall.webp",
  "s-desk.png",
  "s-result.png",
  "s-room-en.png",
  "s-room-th.png",
  "s-sofa.png",
  "s-top-end.mp4",
  "s-top-start.mp4",
  "s-twerk.webm",
  "s1.webp",
  "s2.webp",
  "s3.webp",
  "s4.webp",
  "s5.webp",
  "s6.webp",
  "s7.webp",
  "s8.webp",
  "s9.webp",
  "s10.webp",
  "slap.mp3",
  "sound.mp3",
  "splank_b.jpg",
  "splank_d.png",
  "splank_m.jpg",
  "splank_s.jpg",
  "th.png",
  "transition1.mp4",
  "transition2.mp4",
  "transition3.mp4",
  "transition4.mp4",
  "transition5.mp4",
  "transition7.mp4",
  "transition8.mp4",
  "transition9.mp4",
  "transition10.mp4",
  "transition11.mp4",
  "transition12.mp4",
  "Welcome.mp3",
  "whoosp.mp3",
];

export const preloadAssetUrls = assetNames.map((assetName) => `/assets/${encodeURIComponent(assetName)}`);

const preloadAsset = async (url: string) => {
  const response = await fetch(url, { cache: "force-cache" });
  if (!response.ok) {
    throw new Error(`Could not preload ${url}`);
  }
  await response.blob();
};

export const preloadSiteAssets = async (onProgress: (loadedCount: number, totalCount: number) => void) => {
  const totalCount = preloadAssetUrls.length;
  let loadedCount = 0;
  let nextIndex = 0;
  const workerCount = Math.min(6, totalCount);

  const loadNext = async (): Promise<void> => {
    const index = nextIndex;
    nextIndex += 1;
    if (index >= totalCount) {
      return;
    }

    try {
      await preloadAsset(preloadAssetUrls[index]);
    } catch {
      // A missing or browser-blocked asset should not trap the visitor on loading.
    } finally {
      loadedCount += 1;
      onProgress(loadedCount, totalCount);
    }

    await loadNext();
  };

  onProgress(0, totalCount);
  await Promise.all(Array.from({ length: workerCount }, () => loadNext()));
};
